import DefaultLayout from '@/components/appLayouts/defaultLayout';
import { ToastContainer } from 'react-toastify';
import './globals.css';

export const metadata = {
    title: 'TimViecNhanh - Cơ hội việc làm danh cho mọi người',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <DefaultLayout main={children} />
                <ToastContainer />
            </body>
        </html>
    );
}
